### ISSUE TITLE
Will you accept PR?

### ISSUE THREAD

**Issue by atanughosh01** [AmalRaghk/PYTHON#1]
Hey, will you accept my pull request with "**`hacktoberfest-accepted`**" tag? I'd like to add python codes to it then. Please, do let me as soon as possible if you are up for merging my PR.

**Comment by AmalRaghk** [comment]
> Hey, will you accept my pull request with "**`hacktoberfest-accepted`**" tag? I'd like to add python codes to it then. Please, do let me as soon as possible if you are up for merging my PR.

sure i hope it has some code it in containing python

**Comment by atanughosh01** [comment]
I added two pull requests, **Please accept my pull request with "hacktoberfest-accepted" tag.**
